name: Solidity code coverage

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Solidity code coverage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - run: NO_GAS_ENFORCE=1 npx hardhat coverage
